services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: next-admin-app
    # env_file:
    #   - .env
    ports:
      - "3001:3000"
    environment:
      - HOST=0.0.0.0
    command: npm run dev
